# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: castelao